#!/usr/bin/env bash

set -e

EMPTY=$([ $(ls -A /var/www | egrep -v "._venv|bashrc" | wc -l) -eq 0 ] && echo 'true' || echo 'false')

if [ $EMPTY == 'true' ]; then
    VIRTENV=/var/www/._venv
    PATH=$VIRTENV/bin:$PATH

    virtualenv -p /usr/bin/python2.7 $VIRTENV
    source ${VIRTENV}/bin/activate
    python --version
    pip --version
    pip install --no-cache-dir --upgrade pip
    pip install --no-cache-dir mysqlclient
    pip install --no-cache-dir flask
    mkdir public
    cp -r /usr/src/* /var/www
fi
